export const codeTechs: string[] = [
    " ",
    "react",
    "typscript",
    "tailwind",
    "react",
    "next.js",
    "webgl",
    "three.js",
    "typscript",
    "tailwind",
    "react",
    "next.js",
    "webgl",
    "three.js",
    "typscript",
    "tailwind",
    "next.js",
    "webgl",
    "three.js",
    " "
]

export const designTechs: string[] = [
    " ",
    "figma",
    "photoshop",
    "premiere pro",
    "blender",
    "figma",
    "photoshop",
    "premiere pro",
    "blender",
    "figma",
    "photoshop",
    "premiere pro",
    "blender",
    " ",
]
